#!/usr/bin/env zsh

zsh_add_plugin "zsh-users/zsh-autosuggestions"

zsh_add_plugin "zsh-users/zsh-syntax-highlighting"

# Allows to search in history for substrings like in fish shell
zsh_add_plugin "zsh-users/zsh-history-substring-search"
bindkey "^k" history-substring-search-up
bindkey "^j" history-substring-search-down
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down

zsh_add_plugin "MichaelAquilina/zsh-auto-notify" "auto-notify"

# You Should Use -> reminds to use configured aliases
zsh_add_plugin "MichaelAquilina/zsh-you-should-use" "you-should-use"
export YSU_MESSAGE_POSITION="after"
export YSU_MODE=BESTMATCH